const PLACE_TYPE_LABELS = {
  ca: {
    acai_shop: 'Botiga d\'acai',
    american_restaurant: 'Restaurant americà',
    asian_restaurant: 'Restaurant asiàtic',
    bagel_shop: 'Botiga de bagels',
    bakery: 'Fleca',
    bar: 'Bar',
    bar_and_grill: 'Bar i graella',
    barbecue_restaurant: 'Restaurant de barbacoa',
    bed_and_breakfast: 'Bed & breakfast',
    breakfast_restaurant: 'Restaurant d\'esmorzars',
    brunch_restaurant: 'Restaurant de brunch',
    buffet_restaurant: 'Restaurant bufet',
    cafe: 'Cafè',
    cafeteria: 'Cafeteria',
    candy_store: 'Botiga de llaminadures',
    catering_service: 'Servei de càtering',
    chinese_restaurant: 'Restaurant xinès',
    chocolate_factory: 'Fàbrica de xocolata',
    chocolate_shop: 'Botiga de xocolata',
    coffee_shop: 'Cafeteria especialitzada',
    confectionery: 'Confiteria',
    deli: 'Delicatessen',
    dessert_restaurant: 'Restaurant de postres',
    dessert_shop: 'Botiga de postres',
    diner: 'Diner',
    donut_shop: 'Botiga de dònuts',
    fast_food_restaurant: 'Restaurant de menjar ràpid',
    fine_dining_restaurant: 'Restaurant gastronòmic',
    food_court: 'Zona de restauració',
    food_store: 'Botiga d\'alimentació',
    french_restaurant: 'Restaurant francès',
    greek_restaurant: 'Restaurant grec',
    guest_house: 'Casa d\'hostes',
    hamburger_restaurant: 'Hamburgueseria',
    hostel: 'Hostal',
    hotel: 'Hotel',
    ice_cream_shop: 'Gelateria',
    indian_restaurant: 'Restaurant indi',
    indonesian_restaurant: 'Restaurant indonesi',
    inn: 'Fonda',
    italian_restaurant: 'Restaurant italià',
    japanese_restaurant: 'Restaurant japonès',
    juice_shop: 'Botiga de sucs',
    korean_restaurant: 'Restaurant coreà',
    lebanese_restaurant: 'Restaurant libanès',
    liquor_store: 'Botiga de vins i licors',
    lodging: 'Allotjament',
    market: 'Mercat',
    meal_delivery: 'Menjar a domicili',
    meal_takeaway: 'Menjar per emportar',
    mediterranean_restaurant: 'Restaurant mediterrani',
    mexican_restaurant: 'Restaurant mexicà',
    middle_eastern_restaurant: 'Restaurant de cuina de l\'Orient Mitjà',
    pizza_restaurant: 'Pizzeria',
    pub: 'Pub',
    ramen_restaurant: 'Restaurant de ramen',
    resort_hotel: 'Hotel resort',
    restaurant: 'Restaurant',
    sandwich_shop: 'Entrepans',
    seafood_restaurant: 'Marisqueria',
    spanish_restaurant: 'Restaurant espanyol',
    steak_house: 'Braseria',
    supermarket: 'Supermercat',
    sushi_restaurant: 'Restaurant de sushi',
    tea_house: 'Teteria',
    thai_restaurant: 'Restaurant tailandès',
    turkish_restaurant: 'Restaurant turc',
    vegan_restaurant: 'Restaurant vegà',
    vegetarian_restaurant: 'Restaurant vegetarià',
    vietnamese_restaurant: 'Restaurant vietnamita',
    wine_bar: 'Wine bar',
  },
  es: {
    acai_shop: 'Tienda de acai',
    american_restaurant: 'Restaurante americano',
    asian_restaurant: 'Restaurante asiático',
    bagel_shop: 'Tienda de bagels',
    bakery: 'Panadería',
    bar: 'Bar',
    bar_and_grill: 'Bar y parrilla',
    barbecue_restaurant: 'Restaurante de barbacoa',
    bed_and_breakfast: 'Bed & breakfast',
    breakfast_restaurant: 'Restaurante de desayunos',
    brunch_restaurant: 'Restaurante de brunch',
    buffet_restaurant: 'Restaurante bufé',
    cafe: 'Café',
    cafeteria: 'Cafetería',
    candy_store: 'Tienda de golosinas',
    catering_service: 'Servicio de cátering',
    chinese_restaurant: 'Restaurante chino',
    chocolate_factory: 'Fábrica de chocolate',
    chocolate_shop: 'Tienda de chocolate',
    coffee_shop: 'Cafetería especializada',
    confectionery: 'Confitería',
    deli: 'Delicatessen',
    dessert_restaurant: 'Restaurante de postres',
    dessert_shop: 'Tienda de postres',
    diner: 'Diner',
    donut_shop: 'Tienda de dónuts',
    fast_food_restaurant: 'Restaurante de comida rápida',
    fine_dining_restaurant: 'Restaurante gastronómico',
    food_court: 'Zona de restauración',
    food_store: 'Tienda de alimentación',
    french_restaurant: 'Restaurante francés',
    greek_restaurant: 'Restaurante griego',
    guest_house: 'Casa de huéspedes',
    hamburger_restaurant: 'Hamburguesería',
    hostel: 'Hostal',
    hotel: 'Hotel',
    ice_cream_shop: 'Heladería',
    indian_restaurant: 'Restaurante indio',
    indonesian_restaurant: 'Restaurante indonesio',
    inn: 'Posada',
    italian_restaurant: 'Restaurante italiano',
    japanese_restaurant: 'Restaurante japonés',
    juice_shop: 'Tienda de zumos',
    korean_restaurant: 'Restaurante coreano',
    lebanese_restaurant: 'Restaurante libanés',
    liquor_store: 'Tienda de vinos y licores',
    lodging: 'Alojamiento',
    market: 'Mercado',
    meal_delivery: 'Comida a domicilio',
    meal_takeaway: 'Comida para llevar',
    mediterranean_restaurant: 'Restaurante mediterráneo',
    mexican_restaurant: 'Restaurante mexicano',
    middle_eastern_restaurant: 'Restaurante de Oriente Medio',
    pizza_restaurant: 'Pizzería',
    pub: 'Pub',
    ramen_restaurant: 'Restaurante de ramen',
    resort_hotel: 'Hotel resort',
    restaurant: 'Restaurante',
    sandwich_shop: 'Bocadillería',
    seafood_restaurant: 'Marisquería',
    spanish_restaurant: 'Restaurante español',
    steak_house: 'Asador',
    supermarket: 'Supermercado',
    sushi_restaurant: 'Restaurante de sushi',
    tea_house: 'Tetería',
    thai_restaurant: 'Restaurante tailandés',
    turkish_restaurant: 'Restaurante turco',
    vegan_restaurant: 'Restaurante vegano',
    vegetarian_restaurant: 'Restaurante vegetariano',
    vietnamese_restaurant: 'Restaurante vietnamita',
    wine_bar: 'Wine bar',
  },
  en: {
    acai_shop: 'Acai shop',
    american_restaurant: 'American restaurant',
    asian_restaurant: 'Asian restaurant',
    bagel_shop: 'Bagel shop',
    bakery: 'Bakery',
    bar: 'Bar',
    bar_and_grill: 'Bar and grill',
    barbecue_restaurant: 'Barbecue restaurant',
    bed_and_breakfast: 'Bed & breakfast',
    breakfast_restaurant: 'Breakfast restaurant',
    brunch_restaurant: 'Brunch restaurant',
    buffet_restaurant: 'Buffet restaurant',
    cafe: 'Cafe',
    cafeteria: 'Cafeteria',
    candy_store: 'Candy store',
    catering_service: 'Catering service',
    chinese_restaurant: 'Chinese restaurant',
    chocolate_factory: 'Chocolate factory',
    chocolate_shop: 'Chocolate shop',
    coffee_shop: 'Coffee shop',
    confectionery: 'Confectionery',
    deli: 'Deli',
    dessert_restaurant: 'Dessert restaurant',
    dessert_shop: 'Dessert shop',
    diner: 'Diner',
    donut_shop: 'Donut shop',
    fast_food_restaurant: 'Fast food restaurant',
    fine_dining_restaurant: 'Fine dining restaurant',
    food_court: 'Food court',
    food_store: 'Food store',
    french_restaurant: 'French restaurant',
    greek_restaurant: 'Greek restaurant',
    guest_house: 'Guest house',
    hamburger_restaurant: 'Burger restaurant',
    hostel: 'Hostel',
    hotel: 'Hotel',
    ice_cream_shop: 'Ice cream shop',
    indian_restaurant: 'Indian restaurant',
    indonesian_restaurant: 'Indonesian restaurant',
    inn: 'Inn',
    italian_restaurant: 'Italian restaurant',
    japanese_restaurant: 'Japanese restaurant',
    juice_shop: 'Juice shop',
    korean_restaurant: 'Korean restaurant',
    lebanese_restaurant: 'Lebanese restaurant',
    liquor_store: 'Wine and liquor shop',
    lodging: 'Lodging',
    market: 'Market',
    meal_delivery: 'Meal delivery',
    meal_takeaway: 'Takeaway',
    mediterranean_restaurant: 'Mediterranean restaurant',
    mexican_restaurant: 'Mexican restaurant',
    middle_eastern_restaurant: 'Middle Eastern restaurant',
    pizza_restaurant: 'Pizzeria',
    pub: 'Pub',
    ramen_restaurant: 'Ramen restaurant',
    resort_hotel: 'Resort hotel',
    restaurant: 'Restaurant',
    sandwich_shop: 'Sandwich shop',
    seafood_restaurant: 'Seafood restaurant',
    spanish_restaurant: 'Spanish restaurant',
    steak_house: 'Steakhouse',
    supermarket: 'Supermarket',
    sushi_restaurant: 'Sushi restaurant',
    tea_house: 'Tea house',
    thai_restaurant: 'Thai restaurant',
    turkish_restaurant: 'Turkish restaurant',
    vegan_restaurant: 'Vegan restaurant',
    vegetarian_restaurant: 'Vegetarian restaurant',
    vietnamese_restaurant: 'Vietnamese restaurant',
    wine_bar: 'Wine bar',
  },
};

function humanizePlaceType(value) {
  return String(value || '')
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

function getTranslatedPlaceType(type, language = 'ca') {
  if (!type) {
    return '';
  }

  return (
    PLACE_TYPE_LABELS[language]?.[type]
    || PLACE_TYPE_LABELS.ca[type]
    || humanizePlaceType(type)
  );
}

function getRestaurantPrimaryType(restaurant) {
  return restaurant?.PrimaryType ?? restaurant?.GooglePrimaryType ?? '';
}

export { getRestaurantPrimaryType, getTranslatedPlaceType, humanizePlaceType };
